#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DivisasNative.Droid.Resource", IsApplication=true)]

namespace DivisasNative.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int buttonConvert = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int editTextDollars = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int editTextEuros = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int editTextPesos = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int editTextPounds = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textView2 = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int Accept = 2130968585;
			
			// aapt resource value: 0x7f040003
			public const int Convert = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Dollars = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int Error = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ErrorPesos = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Euros = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int Pesos = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int Pounds = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int Title = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
